### PR TITLE
Project maintenence

### PR DESCRIPTION
**Pull request by DevelopmentByDavid**
I suggest not squashing this particular pr since we may want to revert individual commits. Instead, select "Rebase and merge" from the menu.

See commit messages for details. Pretty straightforward.

Overall, this should reduce the size of the project. On my local machine the size of the .yarn directory went from 681M to 652M, which is a 29M difference.

### CODE REVIEW

**Comment by DevelopmentByDavid** [comment]
@kadey001 You should probably change to the e2e workflow to use file path negations on `app/docs/**` and `app/proxy/**` so that e2e tests will trigger on pure package updates like this PR too. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths

**Comment by kadey001** [comment]
> flow to use file path negations on



> @kadey001 You should probably change to the e2e workflow to use file path negations on `app/docs/**` and `app/proxy/**` so that e2e tests will trigger on pure package updates like this PR too. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths

That's a good idea, no need to run them when docs and proxy is changed, just a waste of resources and time for checks to pass. You want to add that to this PR or in another one?

**Comment by DevelopmentByDavid** [comment]
@kadey001 I'll do it as a separate PR to update the workflow so that e2e still run on this PR.

**Review by kadey001 — DISMISSED** [review]
Seems like everything is working now with that revert so should be ready to merge.

**Comment by kadey001** [comment]
Not sure why checks aren't being run here but I noticed errors when typechecking, I'll try and address them all. Also when running the linter I got this warning
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.6.0

YOUR TYPESCRIPT VERSION: 4.7.4

Please only submit bug reports when using the officially supported version.

=============
```

**Review by kadey001 — DISMISSED** [review]
All checks seem to be passing now.

**Comment by DevelopmentByDavid** [comment]
Don't merge this just yet. I have to go through this more. I'll handle rebasing and double checking that everything is working. I'll also look into why the e2e stuff isn't triggering correctly.

**Comment by kadey001** [comment]
Just wanted to note in here that `@fastify/cookie` types are bugged but `fastify-cookie` (what was used prior to updating fastify) is deprecated in favor of `@fastify/cookie@6.0.0` as stated [here](https://www.npmjs.com/package/fastify-cookie). Currently using any type and // @ts-ignore comments as temporary fix until a better solution is found.

**Pull request merged**
